version: 2.1

orbs:
  codecov: codecov/codecov@1.2.5

commands:
  dependencies:
    description: "Download dependencies"
    parameters:
      shell:
        type: string
        default: "/bin/bash --login -eo pipefail"
    steps:
      - checkout
      - run:
          name: Download deps
          shell: << parameters.shell >>
          command: dart pub get

jobs:
  test:
    docker:
      - image: dart:2.17.0
    steps:
      - dependencies:
          shell: "/bin/bash -eo pipefail"
      - run:
          name: Run tests
          command: |
            dart run build_runner build
            dart run test

workflows:
  version: 2.1
  test:
    jobs:
      - test
