version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

commands:
  dependencies:
    description: "Download dependencies"
    parameters:
      shell:
        type: string
        default: "/bin/bash --login -eo pipefail"
    steps:
      - checkout
      - run:
          name: Download deps
          shell: << parameters.shell >>
          command: pub get

jobs:
  test:
    docker:
      - image: dart:2.18.6-sdk
    steps:
      - dependencies:
          shell: "/bin/bash -eo pipefail"
      - run:
          name: Run tests
          command: |
            dart run build_runner build
            dart test 

workflows:
  version: 2.1
  test-coverage-report:
    jobs:
      - test
